# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '14.0.1.dev0+gba5374836.d20231125'
__version_tuple__ = version_tuple = (14, 0, 1, 'dev0', 'gba5374836.d20231125')
